{
 "title": "Ecto",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Query duration (Inserts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ecto_query_query_time_milliseconds_bucket{query=~\"INSERT.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query duration (Selects)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(ecto_query_query_time_milliseconds_bucket{query=~\"SELECT.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query RPS (Inserts)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ecto_query_total_time_milliseconds_bucket{query=~\"INSERT.*\", le=\"100.0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query RPS (Inserts)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ecto_query_total_time_milliseconds_bucket{query=~\"SELECT.*\", le=\"100.0\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}